galaxy_info:
  role_name: run_create_pvs_image
  author: Joe Shonk
  description: Crete PVS Image from Master
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - citrix
    - pvs
    - image
    - master

dependencies: []
