---
  - name: Mount Citrix PVS ISO
    win_shell: |
      $mountResult = Mount-DiskImage -ImagePath '{{ pvs_server_iso_location }}\{{ pvs_server_iso_file }}'
      $driveLetter = ($mountResult | Get-Volume).DriveLetter
      return $driveLetter
    register: mounted_iso_drive_letter
    changed_when: false
    become: yes

  - name: "Install PVS Server Version {{ pvs_server_version }}"
    win_package:
      path: "{{ mounted_iso_drive_letter.stdout[0] }}:\\{{ pvs_server_install_file_location }}\\{{ pvs_server_install_file }}"
      product_id: "{{ pvs_server_product_id }}"
      arguments: "{{ pvs_server_install_arguments }}"
      state: "{{ pvs_server_install_state }}"

  - name: Dismount Citrix PVS ISO
    win_shell: Dismount-DiskImage -ImagePath '{{ pvs_server_iso_location }}\{{ pvs_server_iso_file }}'
    changed_when: false
    become: yes
