---
  - name: Mount Citrix PVS ISO
    win_shell: |
      $mountResult = Mount-DiskImage -ImagePath '{{ pvs_console_iso_location }}\{{ pvs_console_iso_file }}'
      $driveLetter = ($mountResult | Get-Volume).DriveLetter
      return $driveLetter
    register: mounted_iso_drive_letter
    changed_when: false
    become: yes

  - name: "Install PVS Console Version {{ pvs_console_version }}"
    win_package:
      path: "{{ mounted_iso_drive_letter.stdout[0] }}:\\{{ pvs_console_install_file_location }}\\{{ pvs_console_install_file }}"
      product_id: "{{ pvs_console_product_id }}"
      arguments: "{{ pvs_console_install_arguments }}"
      state: "{{ pvs_console_install_state }}"

  - name: Dismount Citrix PVS ISO
    win_shell: Dismount-DiskImage -ImagePath '{{ pvs_console_iso_location }}\{{ pvs_console_iso_file }}'
    changed_when: false
    become: yes
